-- Eerste datamodel voor Mijn OG. Nog niet gekoppeld aan de prototype-UI.
create table teams (
  id bigint generated by default as identity primary key,
  name text not null,
  sport text not null check (sport in ('softbal','honkbal')),
  season int not null
);

create table players (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique,
  first_name text not null,
  last_name text not null,
  jersey_number text,
  primary_position text
);

create table team_players (
  team_id bigint references teams(id) on delete cascade,
  player_id bigint references players(id) on delete cascade,
  role text default 'player',
  primary key(team_id, player_id)
);

create table events (
  id bigint generated by default as identity primary key,
  team_id bigint references teams(id) on delete cascade,
  google_event_id text unique,
  event_type text not null check (event_type in ('training','wedstrijd','club_event')),
  title text not null,
  starts_at timestamptz not null,
  ends_at timestamptz,
  location text,
  description text
);

create table attendance (
  event_id bigint references events(id) on delete cascade,
  player_id bigint references players(id) on delete cascade,
  status text not null check (status in ('aanwezig','afwezig','onbekend')),
  note text,
  updated_at timestamptz default now(),
  primary key(event_id, player_id)
);

create table batting_stats (
  id bigint generated by default as identity primary key,
  player_id bigint references players(id) on delete cascade,
  team_id bigint references teams(id) on delete cascade,
  season int not null,
  games int default 0,
  at_bats int default 0,
  hits int default 0,
  doubles int default 0,
  triples int default 0,
  home_runs int default 0,
  rbi int default 0,
  walks int default 0,
  hit_by_pitch int default 0,
  stolen_bases int default 0
);

create table highlights (
  id bigint generated by default as identity primary key,
  player_id bigint references players(id) on delete set null,
  team_id bigint references teams(id) on delete set null,
  title text not null,
  description text,
  highlight_type text,
  is_clubwide boolean default true,
  published_at timestamptz default now()
);


-- Persoonlijke externe agenda-koppelingen.
-- In productie via RLS alleen leesbaar/schrijfbaar door de eigenaar.
create table user_calendar_feeds (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  source text not null check (source in ('knbsb_foys_ics','google_calendar')),
  feed_url text not null,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(auth_user_id, source)
);

alter table user_calendar_feeds enable row level security;

create policy "users can read own calendar feeds"
  on user_calendar_feeds for select
  using (auth.uid() = auth_user_id);

create policy "users can insert own calendar feeds"
  on user_calendar_feeds for insert
  with check (auth.uid() = auth_user_id);

create policy "users can update own calendar feeds"
  on user_calendar_feeds for update
  using (auth.uid() = auth_user_id)
  with check (auth.uid() = auth_user_id);

create policy "users can delete own calendar feeds"
  on user_calendar_feeds for delete
  using (auth.uid() = auth_user_id);
